Starknet-Foundry
Web3Arabs/starknet-course pull request #33
Opened 2024-10-03 20:25 UTC by malakbenh

2024-10-03 20:26 UTC, malakbenh commented
Starknet-Foundry-commit

2024-10-09 12:35 UTC, KhairallahA requested changes
great work!

2024-10-09 12:35 UTC, KhairallahA commented on course/8-Get-Started-with-starkent-foundry.md
> +<div dir="rtl">
i don't think we need to add this line, you can delete it.

2024-10-09 12:35 UTC, KhairallahA commented on course/8-Get-Started-with-starkent-foundry.md
> +</div>
same

2024-10-12 12:15 UTC, merged

2024-10-12 12:18 UTC, KhairallahA commented
@malakbenh merged!